config/routes.rb
Rails.application.routes.draw do
  devise_for :masters

  get 'posts/edit', to: 'posts#edit', as: 'post/edit'
  get 'posts/:id/edit', to: 'master#edit'
  put 'posts/update', to: 'posts#update', as: 'posts/update'

  get 'album/', to: 'album#index'
  get 'album/:id', to: 'album#show', as: 'album/show'

  root to: 'posts#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :photos
end

app/models/master.rb
class Master < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :album
	has_attached_file :resource, PAPERCLIP_STORAGE_OPTS

  validates_attachment_content_type :resource, content_type: /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/album_controller.rb
class AlbumController < ApplicationController
	before_action :authenticate_user!, only: [:edit, :update, :new, :create, :destroy]

	def index
		@albums = Album.all.eager_load(:photos)
	end

	def show
		@album = Album.find(params[:id])
		@photos = @album.photos
	end

	def edit
	end

	def update
	end

	def create
	end

	def destroy
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    protected

      def after_sign_in_path_for(resource)
        # return the path based on resource
        post_edit_path
      end
end

app/controllers/master_controller.rb
class MasterController < ApplicationController
	before_filter :authenticate_user!

	def edit
		@post = Post.find_by(params[:id])
	end

	def update
		@post.assign_attributes title: params[:title] 
		@post.assign_attributes content: params[:content]
		@post.save
	end

	private
	def get_params
		params.require(:post).permit([:title, :content])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:edit, :update, :new, :create, :destroy]
	def index
		@post = Post.first
	end

	def show

	end

	def edit
		@post = Post.first
	end

		
	def update
		@post = Post.first
		@post.assign_attributes title: params[:post][:title] 
		@post.assign_attributes content: params[:post][:content]
		@post.save
	end

	def new
	end

	def create
	end

	def destroy
	end

	private
		def get_param
			params.require(:post).permit([:title, :content])
		end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/master_helper.rb
module MasterHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/album/index.html.haml
%main
  .post
    .post-title
      %h1 Albums
    .container-fluid
      .row#mas
        - @albums.each do |a|
          .col-xs-4.col-md-3.no-gutter.masbox
            .imgbox
              = link_to album_show_path(id: a.id) do
                = image_tag a.photos.shuffle.first.resource.url(:medium), class: 'img img-responsive'
                .album-title
                  %p= a.name

app/views/album/show.html.haml
%main
  .post
    .post-title
      %h1= @album.name
    .container-fluid
      .row
        .col-sm-12
          #photo-show
            - @photos.each do |p|
              .item.item-show
                = image_tag p.resource.url, alt: p.name, class: 'img img-responsive'
        .col-sm-12
          .owl-carousel
            - @photos.each do |p|
              .item
                = image_tag p.resource.url(:medium), alt: p.name, class: 'img img-responsive'

app/views/layouts/_caption.html.haml
.background-image
  = image_tag 'lake.jpg', class: 'img img-responsive'
  .overlay
.container-fluid
  .row
    .col-md-7.col-sm-12
      .caption
        %h1 GORDON YIP
        %h1 WEB DEVELOPER
        %p.hidden-xs.hidden-sm SHIFTING FROM AVIATION, A NOT TOO YOUNG PADAWAN. A DREAMER DREAMS SHE NEVER DIE, AND DON'T BELIEVE THAT THEY'RE GONNA GET AWAY FROM THEIR SUMMER. 
    .col-md-5.col-sm-12.no-gutter
      .feature-image
        .circle
          = image_tag 'head01.jpg'

app/views/layouts/_footer.html.haml
%footer
  .container-fluid
    %row.heading
      .col-md-12
        %p proudly presented to you by Gordon Yip, &copy 2015.

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-inverse
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{type: 'button', :"aria-expanded" => false, data: {toggle: 'collapse', target: '#nav_head'}}
          %span.sr-only Toggle nav
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to root_path do
          %h4 GoRdoN
      .collapse.navbar-collapse#nav_head
        %ul.nav.navbar-nav
          -#
            %li
              = link_to 'Blog', posts_edit_path
          %li
            = link_to 'Photo', album_path
          %li
            = link_to 'About', ''

app/views/layouts/album.html.haml
!!!
%html
  %head
    %meta{name: 'viewport',:content => "width=device-width, initial-scale=1.0; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Gordon | Showcast
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Roboto:500', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/gsap/1.17.0/TweenMax.min.js'
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: 'viewport',:content => "width=device-width, initial-scale=1.0; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Gordon | Showcast
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Roboto:500', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/gsap/1.17.0/TweenMax.min.js'
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container-fluid
      .row
        .col-sr-12.col-md-10.col-md-offset-1
          = yield
    = render 'layouts/footer'

    

app/views/layouts/posts.html.haml
!!!
%html
  %head
    %meta{name: 'viewport',:content => "width=device-width, initial-scale=1.0; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Gordon | Showcast
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Roboto:500', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/gsap/1.17.0/TweenMax.min.js'
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = render 'layouts/caption'
    = yield
    = render 'layouts/footer'

app/views/posts/edit.html.haml
%main
  .container-fluid
    .row
      .col-xs-12.col-md-10.col-md-push-1
        .post
          %h1 Edit Post No. #{@post.id}
          %p.notice
          %p.alert
          = simple_form_for @post, as: :post, url: posts_update_path, method: :put, remote: true do |f|
            = f.input :title, label: 'Post Title', placeholder: 'Title here', value: @post.title
            %br
            = f.input :content, as: :text, label: 'Content', placeholder: 'Content', input_html: {value: @post.content, rows: 20}
            = f.button :submit, 'Submit', class: 'btn'

app/views/posts/index.html.haml
-# check color 
  %h1 This is index page.
  .row
    - (1..18).each do |i|
      .col-md-2{style: "background: \$c#{i}", class: "colour_#{i}"}
        %p #{i}
%main
  .container-fluid
    .row
      .col-xs-12.col-md-12
        .heart-container
          #heart
    .row
      .col-sm-12.col-md-10.col-md-push-1
        .post
          .post-title
            %h1= @post.title
            %small= @post.subtitle
          .post-content
            %p= simple_format @post.content
-#
  .row.container-fluid
    .col-md-12.image
      = image_tag 'lake.jpg', class: 'img img-responsive'
      .overlay
        %h1 OVER THE HILLS & FAR AWAY
        %p EMERALD MORAINE LAKE, ALBERTA, CANADA

app/views/posts/show.html.haml
%main
  .container-fluid
    .row
      .col-xs-12.col-md-10.col-md-push-1
        .post
          .post-title
            %h1= @post.title
          .post-content
            %p= simple_format @post.content

app/views/posts/update.js.haml
window.history.back();